version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /web-app/public
    ports:
      - 80:80
    volumes:
      - ./web-app:/web-app
    networks:
      - webnet
#  web:
#    build:
#      context: ./
#      dockerfile: web.dockerfile
#    working_dir: /public
#    volumes:
#      - ./web-app:/web-app
#    ports:
#      - 8080:8080
networks:
  webnet: