version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /web-app/public
    ports:
      - 80:80
#    volumes:
#      - ./web-app:/web-app
    networks:
      - webnet
    environment:
      - APP_KEY=base64:sf+TeOK14bHa/pqupMwHbV5MUBFeZF/OPFh+LU++0w8=
      - APP_DEBUG=true
      - APP_URL=http://localhost
networks:
  webnet: